name: insta_clone
description: Instagram clone built with Flutter Web and Supabase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  supabase_flutter: ^2.3.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.0
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  image_picker: ^1.0.7
  flutter_staggered_grid_view: ^0.7.0
  dotted_border: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
